novel_website/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('novel/',include('novel.urls')),
]

novel_website/novel/urls.py
from django.urls import path
from . import views

app_name = 'novel'

urlpatterns = [
    path('',views.index,name = 'index'),
    path('search/',views.search,name = 'search'),
    path('home/',views.home,name = 'home'),
    path('search/<int:book_pk>/<int:book_id>/',views.book,name = 'book'),
    path('home/<int:book_pk>/<int:book_id>/',views.book,name = 'book'),
    path('search/<int:book_pk>/<int:book_id>/<int:chapter_id>.html/',
         views.chapter,name='chapter'),
    path('search/<int:book_pk>/<int:book_id>/download/',views.download,name = 'download'),
    path('home/<int:book_pk>/<int:book_id>/download/',views.download,name = 'download'),
    path('home/<int:book_pk>/<int:book_id>/<int:chapter_id>.html/',
         views.chapter,name='chapter'),
]

novel_website/novel/models.py
from django.db import models

# Create your models here.

novel_website/novel/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from .x23uscom import *
from .spider import Spider
from .dingdian import Novel

def index(request):

    context = {}
    return render(request,'novel/index.html',context)

def search(request):
    s_info = request.POST
    novel_name = s_info['novel_name']

    novel_obj = X23usCom(novel_name)
    novel_info = novel_obj.index()
    if isinstance(novel_info,(dict,)):
        url = novel_info['url']
        chapter = Spider(url)
        info = chapter.info(chapter_url = '<a class="read" href="https://www.x23us.com/html/(.*?)" title=".*?">章节列表</a>',
                            )
        
        arg = info['chapter_url'][0].split('/')
        return HttpResponseRedirect(reverse('novel:book',args = (arg[0],arg[1])))
    else:
        last_info = novel_obj.info()
        context = {'last_info':last_info}
        return render(request,'novel/search.html',context)

def book(request,book_pk,book_id):
    url = 'https://www.x23us.com/html/{}/{}/'.format(book_pk,book_id)

    book_name = '<meta name="og:novel:book_name" content="(.*?)"/>'
    book_author = '<meta name="og:novel:author" content="(.*?)"/> '
    book_info = '<td class="L"><a href="(.*?)">(.*?)</a></td>'

    x = Spider(url = url)
    info_dict = x.info(book_name = book_name,
                       book_author = book_author,
                       book_info = book_info,
                       )
    context = info_dict
    detail_url = 'https://www.x23us.com/book/{}'.format(book_id)
    novel_img = '<img style="padding:7px; border:1px solid #E4E4E4; \
width:120px; height:150px; margin:0 25px 0 15px;" alt=".*?" src="(.*?)"  onerror=".*?"/>'
    novel_detail = '<p>(.*?)<br /></p><p style="display:none" id="sidename">.*?</p>'
    n = Spider(url = detail_url)
    detail_dict = n.info(novel_img = novel_img,
                         )

    context.update(detail_dict)

    return render(request,'novel/book.html',context)

def download(request,book_pk,book_id):
    url = 'https://www.x23us.com/html/{}/{}/'.format(book_pk,book_id)
    x = Novel(url)
    y = x.save_txt()
    return HttpResponse(y)
0

def home(request):
    url = 'https://www.x23us.com'
    img_reg = '<dd><a href=".*?" target="_blank"><img src="(.*?)" alt=".*?"></a><br /><a href=".*?" target="_blank">.*?</a></dd>'
    detail_reg = '<dd><a href=".*?" target="_blank"><img src=".*?" alt=".*?"></a><br /><a href="https://www.x23us.com/html/(.*?)" target="_blank">.*?</a></dd>'
    name_reg = '<dd><a href=".*?" target="_blank"><img src=".*?" alt=".*?"></a><br /><a href=".*?" target="_blank">(.*?)</a></dd>'

    the_html = Spider(url = url)
    the_info = the_html.info(img_reg = img_reg,
                       detail_reg = detail_reg,
                       name_reg = name_reg,
                       )
    last_dict = {}
    for i in range(len(the_info['name_reg'])):
        last_dict[the_info['name_reg'][i]] = {
		'img_url':the_info['img_reg'][i],
		'detail_url':the_info['detail_reg'][i],
                'fenjie_url':the_info['detail_reg'][i].split('/'),
		}
    #print(last_dict)
    ty_reg = '<li><p class="ul1">(.*?)《<a class="poptext" href=".*?" target="_blank">.*?</a>》</p><p class="ul2">\
<a href=".*?" target="_blank">.*?</a></p><p>.*?</p>.*?</li>'
    bknm_reg = '<li><p class="ul1">.*?《<a class="poptext" href=".*?" target="_blank">(.*?)</a>》</p><p class="ul2">\
<a href=".*?" target="_blank">.*?</a></p><p>.*?</p>.*?</li>'
    dt_reg = '<li><p class="ul1">.*?《<a class="poptext" href="https://www.x23us.com/html/(.*?)" target="_blank">.*?</a>》</p><p class="ul2">\
<a href=".*?" target="_blank">.*?</a></p><p>.*?</p>.*?</li>'
    cata_reg = '<li><p class="ul1">.*?《<a class="poptext" href=".*?" target="_blank">.*?</a>》</p><p class="ul2">\
<a href=".*?" target="_blank">(.*?)</a></p><p>.*?</p>.*?</li>'
    au_reg = '<li><p class="ul1">.*?《<a class="poptext" href=".*?" target="_blank">.*?</a>》</p><p class="ul2">\
<a href=".*?" target="_blank">.*?</a></p><p>(.*?)</p>.*?</li>'
    tm_reg = '<li><p class="ul1">.*?《<a class="poptext" href=".*?" target="_blank">.*?</a>》</p><p class="ul2">\
<a href=".*?" target="_blank">.*?</a></p><p>.*?</p>(.*?)</li>'
    zxzj_reg = '<li><p class="ul1">.*?《<a class="poptext" href=".*?" target="_blank">.*?</a>》</p><p class="ul2">\
<a href="https://www.x23us.com/html/(.*?)" target="_blank">.*?</a></p><p>.*?</p>.*?</li>'

    zx_info = the_html.info(ty_reg = ty_reg,
                            bknm_reg = bknm_reg,
                            dt_reg = dt_reg,
                            cata_reg = cata_reg,
                            au_reg = au_reg,
                            tm_reg = tm_reg,
                            zxzj_reg = zxzj_reg,
                            )
    zx_dict = {}
    for x in range(12):
        zx_dict[zx_info['bknm_reg'][x]] = {
            'ty_reg':zx_info['ty_reg'][x],
            'dt_reg':zx_info['dt_reg'][x],
            'cata_reg':zx_info['cata_reg'][x],
            'au_reg':zx_info['au_reg'][x],
            'tm_reg':zx_info['tm_reg'][x],
            'fenj_url':zx_info['dt_reg'][x].split('/'),
            'zxzj_reg':zx_info['zxzj_reg'][x],
            }
    context = {'last_dict':last_dict,'zx_dict':zx_dict}
    return render(request,'novel/home.html',context)
     
def chapter(request,book_pk,book_id,chapter_id):
    url = 'https://www.x23us.com/html/{}/{}/{}.html'.format(book_pk,book_id,chapter_id)

    chapter_title = '<title>(.*?)</title>'
    chapter_content = '<dd id="contents">(.*)'

    previous_page = '<dd id="footlink"><a href="/html/(.*?)">上一页</a>\
<a href="/html/(.*?)" title=".*?">返回章节列表</a>\
<a href="/html/(.*?)">下一页</a></dd>'

    x = Spider(url = url)
    info_list = x.info(chapter_title = chapter_title,
                       chapter_content = chapter_content,
                       previous_page = previous_page,
                       )
    return render(request,'novel/chapter.html',context = info_list)

    
    
    

novel_website/novel/templates/novel/book.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->

    <title>小说章节页面</title>

    <!-- Bootstrap 核心CSS文件 -->
    <link href="{% static 'novel/css/bootstrap.min.css' %}" rel="stylesheet">
    <script type="text/javascript" src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <style type="text/css">

          body{
            background: url("{% static 'novel/image/1.jpg' %}");
            background-attachment: fixed;
            background-size: 100%;
        }

        .fa{display: inline-block;top: 27px;left: 6px;position: relative;color: #ccc;}
        input[type="text"],input[type="password"]{padding-left:26px;}
        #checkbox{padding-left:21px;}
        
        .form-signin-heading{
            text-align: center;
            color: #337ab7;
        }
        h3{
            display: inline-block;    
            margin:120px auto 0;
        }
        .the_title{
            margin-top: 30px;
            background: rgba(255,255,255,0.7);
        }
        .tabbable{
            margin: 10px auto 0;
            padding-top: 20px;
            background: rgba(255,255,255,0.6);
        }
        .one,.two{
            background: rgba(255,255,255,0.9);
        }
        .footer{
            background: rgba(255,255,255,0.8);
            position: fixed;
            left: 460px;
            bottom: 6px;
        }
        .footer .foot{
            margin: 0 auto;
        }
        .zj{
            border:1px solid rgba(255,255,255,1);
        }
        .a12{
            animation-name:myanimation;
            animation-duration:12s;
            /*变换时间*/
            animation-delay:2s;
            /*动画开始时间*/
            animation-iteration-count:infinite;
            /*下一周期循环播放*/
            animation-play-state:running;
            /*动画开始运行*/
        }
        @keyframes myanimation{
            0%   {left: 300px;}
            34%  {left: 450px;}
            67%  {left: 600px;}
            100% {left: 450px;}
        }
        /*.zj{
            margin-right: 10px;
            display: inline-block;
        }*/
        .zj{
            position: relative;
            /*color: #9f00ff;*/
            text-decoration: none;
            display: block;
            /*padding: 10px 20px;*/ 
            border: 1px solid #dedede;
            transition: all 0.6s ease-in;
        }
        .zj:before,.zj:after{
            content: '';
            display: block;
            position: absolute;
            box-sizing: border-box;
            border: 1px solid transparent;
            width: 0;
            height: 0;
        }
        .zj:before {
          bottom: 0;
          right: 0;
          transition: border-color 0s ease-in 0.4s,width 0.2s ease-in 0.2s,height 0.2s ease-in;
      }
      .zj:after{
          top: 0;
          left: 0;
          transition: border-color 0s ease-in 0.8s,width 0.2s ease-in 0.6s,height 0.2s ease-in 0.4s;
      }
      .zj:hover:after,.zj:hover:before {
          width: 100%;
          height: 100%;
      }
      .zj:hover:before {
          border-bottom-color: #31708f;
          border-left-color: #31708f;
          transition: border-color 0s ease-out 0.4s,width 0.2s ease-out 0.4s,height 0.2s ease-out 0.6s;
      }
      .zj:hover:after {
          border-top-color: #31708f;
          border-right-color: #31708f;
          transition: width 0.2s ease-out,height 0.2s ease-out 0.2s;
      }
  </style>
</head>

<body>

   <div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 align="center">{{book_name.0}} <small>作者：{{book_author.0}}</small></h2>
            <div class="col-sm-6 col-md-3">
                <h4 class="" style="text-align: left;color: #337ab7;">重新搜索</h4>
                <form class="form-signin" action="{% url 'novel:search' %}" method="post" style="margin-top: -16px;">
                            {% csrf_token %}
                            <i class="fa fa-user fa-lg"></i>
                            <label for="inputName" class="sr-only">账号：</label>
                            <input type="text" name="novel_name" id="inputName" class="form-control" placeholder="请输入关键字" required autofocus>

                            <a href="{% url 'novel:home' %}"><button class="btn btn-info pull-right" type="button" style="margin-top: 12px;">排行榜</button></a>
                            <button class="btn btn-warning pull-right" style="margin-top: 12px;" type="submit">一键搜索</button>

                        </form>
            </div>
            <img src="{{novel_img.0}}" class="a12" style="width: 160px;height: 188px;position: relative;left: 300px;">
        </div>
    </div>

    <div class="row tabbable">

            {%for i in book_info%}

            <div class="col-md-3" style="white-space: nowrap;text-overflow: ellipsis;overflow: hidden;">    
                    <a href ='{{i.0}}' style="text-decoration: none;"><div class="alert alert-info zj" style="white-space: nowrap;text-overflow: ellipsis;overflow: hidden;" align="center" role="alert">{{i.1}}
                    </div></a>              
                </div>
                {%endfor%}  
            </div>
        </div>
        </div> 

    <!-- 引用的样式部分，不属于内容： -->
    <!-- jquery部分： -->
    <script type="text/javascript" src="{% static 'novel/js/jquery-3.3.1.min.js' %}"></script>
    <!-- Bootstrap部分： -->
    <script type="text/javascript" src="{% static 'novel/js/bootstrap.min.js' %}"></script>
</body>
</html>

novel_website/novel/templates/novel/chapter.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->

  <title>小说章节阅读</title>

  <!-- Bootstrap 核心CSS文件 -->
  <link href="{% static 'novel/css/bootstrap.min.css' %}" rel="stylesheet">

  <style type="text/css">

          body{
            background: url("{% static 'novel/image/1.jpg' %}");
            background-attachment: fixed;
            background-size: 100%;
          }

          .fa{display: inline-block;top: 27px;left: 6px;position: relative;color: #ccc;}
          input[type="text"],input[type="password"]{padding-left:26px;}
          #checkbox{padding-left:21px;}
          
          .form-signin-heading{
            text-align: center;
            color: #337ab7;
          }
          h3{
            display: inline-block;    
            margin:120px auto 0;
          }
          .the_title{
            margin-top: 30px;
            background: rgba(255,255,255,0.7);
          }
          .tabbable{
            margin: 40px auto 0;
            background: rgba(255,255,255,0.8);
          }
          .one,.two{
            background: rgba(255,255,255,0.9);
          }
          .footer{
            background: rgba(255,255,255,0.8);
            position: fixed;
            left: 460px;
            bottom: 6px;
          }
          .footer .foot{
            margin: 0 auto;
          }
        </style>
      </head>

      <body>

       <div class="container">
         <div class="row">
          <h2 align="center">{{chapter_title.0}} <small></small></h2>
          <div class="col-md-12 tabbable">
            <nav aria-label="Page navigation" align='center'>
              <ul class="pagination">
                <li><a href="/novel/search/{{previous_page.0.0}}">上一页</a></li>
                <li><a href="/novel/search/{{previous_page.0.1}}">回到章节目录</a></li>
                <li><a href="/novel/search/{{previous_page.0.2}}">下一页</a></li>
              </ul>
            </nav>
            <p class="lead">{{chapter_content.0|safe}}</p>
            <nav aria-label="Page navigation" align='center'>
              <ul class="pagination">
                <li><a href="/novel/search/{{previous_page.0.0}}">上一页</a></li>
                <li><a href="/novel/search/{{previous_page.0.1}}">回到章节目录</a></li>
                <li><a href="/novel/search/{{previous_page.0.2}}">下一页</a></li>
              </ul>
            </nav>
          </div>
        </div>
      </div>

      <!-- 引用的样式部分，不属于内容： -->
      <!-- jquery部分： -->
      <script type="text/javascript" src="{% static 'novel/js/jquery-3.3.1.min.js' %}"></script>
      <!-- Bootstrap部分： -->
      <script type="text/javascript" src="{% static 'novel/js/bootstrap.min.js' %}"></script>
    </body>
    </html>

novel_website/novel/templates/novel/home.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
	<title>风云排行榜</title>

	<!-- Bootstrap 核心CSS文件 -->
	<link href="{% static 'novel/css/bootstrap.min.css' %}" rel="stylesheet">
	<script type="text/javascript" src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script> 

	<style type="text/css">
    
          body{
          	background: url("{% static 'novel/image/1.jpg' %}");
            background-attachment: fixed;
          	background-size: 100%;
          }

          .fa{display: inline-block;top: 27px;left: 6px;position: relative;color: #ccc;}
          input[type="text"],input[type="password"]{padding-left:26px;}
          #checkbox{padding-left:21px;}

          .form-signin-heading{
          	text-align: center;
          	color: #337ab7;
          }
          h3{
          	display: inline-block;    
          	margin:80px auto 0;
          }
          .the_title{
          	margin-top: 30px;
          	/*background: rgba(255,255,255,0.7);*/
          }
          .tabbable{
          	margin: 40px auto 0;
          	background: rgba(255,255,255,0.7);
          }
          .one,.two{
          	background: rgba(255,255,255,0.9);
          }
          .footer{
          	background: rgba(255,255,255,0.8);
          	position: fixed;
          	left: 460px;
          	bottom: 6px;
          }
          .zj{
            position: relative;
            /*color: #9f00ff;*/
            text-decoration: none;
            display: block;
            /*padding: 10px 20px;*/ 
            border: 1px solid #dedede;
            transition: all 0.6s ease-in;
        }
        .zj:before,.zj:after{
            content: '';
            display: block;
            position: relative;
            box-sizing: border-box;
            border: 1px solid transparent;
            width: 0;
            height: 0;
        }
        .zj:before {
          bottom: 0;
          right: 0;
          transition: border-color 0s ease-in 0.4s,width 0.2s ease-in 0.2s,height 0.2s ease-in;
      }
      .zj:after{
          top: 0;
          left: 0;
          transition: border-color 0s ease-in 0.8s,width 0.2s ease-in 0.6s,height 0.2s ease-in 0.4s;
      }
      .zj:hover:after,.zj:hover:before {
          width: 100%;
          height: 100%;
      }
      .zj:hover:before {
          border-bottom-color: #31708f;
          border-left-color: #31708f;
          transition: border-color 0s ease-out 0.4s,width 0.2s ease-out 0.4s,height 0.2s ease-out 0.6s;
      }
      .zj:hover:after {
          border-top-color: #31708f;
          border-right-color: #31708f;
          transition: width 0.2s ease-out,height 0.2s ease-out 0.2s;
      }
      </style>
  </head>

  <body>

  	<div class="container">
  		<div class="row tabbable">
  			<h2 class="form-signin-heading the_title">小说风云榜</h2>
        
  			<div class="col-sm-6 col-md-3">
  				<h4 class="" style="text-align: left;color: #337ab7;">搜索小说</h4>
  				<form class="form-signin" action="{% url 'novel:search' %}" method="post" style="margin-top: -16px;">
                            {% csrf_token %}
                            <i class="fa fa-user fa-lg"></i>
                            <label for="inputName" class="sr-only">关键字：</label>
                            <input type="text" name="novel_name" id="inputName" class="form-control" placeholder="请输入关键字" required autofocus>

                            <!-- <i class="fa fa-user fa-lg"></i> -->
                            <a href="{% url 'novel:home' %}"><button class="btn btn-info pull-right" type="button" style="margin-top: 12px;">排行榜</button></a>
                            <button class="btn btn-warning pull-right" style="margin-top: 12px;" type="submit">一键搜索</button>

                        </form>
        <h3 style="color: #337ab7;">最近更新</h3>
        {% for bk_nm,value in zx_dict.items %}
        <div class="thumbnail zj">
          <div class="caption">
            <h4 style="margin: 0 auto 0">书名：<a href="{{value.fenj_url.0}}/{{value.fenj_url.1}}">{{bk_nm}}</a></h4>
            <p  style="white-space: nowrap;text-overflow: ellipsis;overflow: hidden;">作者：{{value.au_reg}}<br>
              类型：{{value.ty_reg}}<br>
                更新日期：{{value.tm_reg}}<br>
                <a href="{{value.zxzj_reg}}">最新章节：{{value.cata_reg}}</a>
                </p>
          </div>
        </div>
        {% endfor %}  
  			</div>
  			<div class="col-md-9">
  			{% for book_name,value in last_dict.items %}
  			<div class="col-md-3">
  				<div class="thumbnail">
  					<img src="{{value.img_url}}" style="margin-top: 10px;width: 160px;height: 188px;white-space: nowrap;text-overflow: ellipsis;overflow: hidden;" alt="...">
  					<div class="caption">
						<h4 style="margin: 0 auto 0">书名：<a href="{{value.fenjie_url.0}}/{{value.fenjie_url.1}}">{{book_name}}</a></h4>
                <p></p>
  							<p><a href="{{value.detail_url}}" class="btn btn-primary btn-sm" role="button">阅读全书</a> <a href="{{value.fenjie_url.0}}/{{value.fenjie_url.1}}/download/" class="btn btn-info btn-sm" role="button" target="view_window" download="{{book_name}}.txt" onclick="myfun()">下载TXT</a></p>

  					</div>
  				</div>
  			</div>
  			{% endfor %}
        </div>
  		</div>
  		
  	</div>
  	<script type="text/javascript">
  		function myfun(){
  			// alert('正在下载，请稍等...')
  			swal('正在下载，请稍等...')
  		}
  	</script>
  	<script type="text/javascript" src="{% static 'novel/js/jquery-3.3.1.min.js' %}"></script>
  	<!-- Bootstrap部分： -->
  	<script type="text/javascript" src="{% static 'novel/js/bootstrap.min.js' %}"></script>
  </body>
  </html>

novel_website/novel/templates/novel/index.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>小说搜索页</title>
    <link href="{% static 'novel/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'novel/css/1.css' %}" rel="stylesheet">
    <style type="text/css">
 
        body{
            background: url("{% static 'novel/image/1.jpg' %}");
            background-size: cover;
        }

        .btn{
        	font-size: 20px;
        	margin-top: 20px;
        }

     </style>
  </head>

  <body>
    <div class="container">
      <form class="form-signin" action="{% url 'novel:search'%}" method="post">
      {%csrf_token%}
      <h2 class="form-signin-heading">小说搜索首页</h2>
        <label for="inputPassword" class="sr-only">关键字</label>
        <input type="text" id="inputPassword" class="form-control" placeholder="搜索关键字" required name="novel_name">
        <a href="{% url 'novel:home' %}"><button class="btn btn-success pull-right" type="button">排行榜</button></a>
        <button class="btn btn-primary pull-right" type="submit">搜索</button>
      </form>

    </div>
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

novel_website/novel/templates/novel/search.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
		<title>小说搜索结果</title>
	<!-- Bootstrap 核心CSS文件 -->
	<link href="{% static 'novel/css/bootstrap.min.css' %}" rel="stylesheet">
	<script type="text/javascript" src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script> 
	<style type="text/css">
  
          body{
          	background: url("{% static 'novel/image/1.jpg' %}");
          	background-attachment: fixed;
          	background-size: 100%;
          }
          .fa{display: inline-block;top: 27px;left: 6px;position: relative;color: #ccc;}
          input[type="text"],input[type="password"]{padding-left:26px;}
          #checkbox{padding-left:21px;}

          .form-signin-heading{
          	text-align: center;
          	color: #337ab7;
          }
          h3{
          	display: inline-block;    
          	margin:120px auto 0;
          }
          .the_title{
          	margin-top: 30px;
          }
          .tabbable{
          	margin: 40px auto 0;
          	background: rgba(255,255,255,0.7);
          }
          .one,.two{
          	background: rgba(255,255,255,0.9);
          }
      
          .footer .foot{
          	margin: 0 auto;
          }
          .zj{
            position: relative;
            /*color: #9f00ff;*/
            text-decoration: none;
            /*display: block;*/
            /*padding: 10px 20px;*/ 
            border: 1px solid #dedede;
            transition: all 0.6s ease-in;
        }
        /*.zj:hover{
            color: #0012ff;
            border: 1px solid #4488ff;
        }*/
        .zj:before,.zj:after{
            content: '';
            display: block;
            position: relative;
            box-sizing: border-box;
            border: 1px solid transparent;
            width: 0;
            height: 0;
        }
        .zj:before {
          bottom: 0;
          right: 0;
          transition: border-color 0s ease-in 0.4s,width 0.2s ease-in 0.2s,height 0.2s ease-in;
      }
      .zj:after{
          top: 0;
          left: 0;
          transition: border-color 0s ease-in 0.8s,width 0.2s ease-in 0.6s,height 0.2s ease-in 0.4s;
      }
      .zj:hover:after,.zj:hover:before {
          width: 100%;
          height: 100%;
      }
      .zj:hover:before {
          border-bottom-color: #337ab7;
          border-left-color: #337ab7;
          transition: border-color 0s ease-out 0.4s,width 0.2s ease-out 0.4s,height 0.2s ease-out 0.6s;
      }
      .zj:hover:after {
          border-top-color: #337ab7;
          border-right-color: #337ab7;
          transition: width 0.2s ease-out,height 0.2s ease-out 0.2s;
      }
      </style>
  </head>

  <body>

  	<div class="container">
  		<div class="row tabbable">
  			<h2 class="form-signin-heading the_title">小说搜索结果</h2>
  			
  			{% for book_name,value in last_info.items %}
  			<div class="col-sm-6 col-md-3">
  				<div class="thumbnail zj">
  					<div class="caption">
						<h4 style="margin: 20px auto 0">书名：<a href="{{value.url}}">{{book_name}}</a></h4>
  							<p  style="white-space: nowrap;text-overflow: ellipsis;overflow: hidden;">作者：{{value.author}}<br>
								状态：{{value.statu}}<br>
								最新章节：<font style="">{{value.latest_chapter}}</font>
  							</p>

  							<p><a href="{{value.url}}" class="btn btn-primary" role="button">阅读全书</a> <a href="{{value.fenjie_url.0}}/{{value.fenjie_url.1}}/download/" class="btn btn-info" role="button" target="view_window" download="{{book_name}}.txt" onclick="myfun()">下载TXT</a></p>
  					
  					</div>
  				</div>
  			</div>
  			{% endfor %}
        <div class="col-sm-6 col-md-3">
          <h4 class="" style="text-align: left;color: #337ab7;">重新搜索</h4>
          <form class="form-signin" action="{% url 'novel:search' %}" method="post" style="margin-top: -16px;">
                            {% csrf_token %}
                            <i class="fa fa-user fa-lg"></i>
                            <label for="inputName" class="sr-only">账号：</label>
                            <input type="text" name="novel_name" id="inputName" class="form-control" placeholder="请输入关键字" required autofocus>

                            <a href="{% url 'novel:home' %}"><button class="btn btn-info pull-right" type="button" style="margin-top: 12px;">排行榜</button></a>
                            <button class="btn btn-warning pull-right" style="margin-top: 12px;" type="submit">一键搜索</button>

                        </form>
        </div>
  		</div>
  	</div>
  	<script type="text/javascript">
  		function myfun(){
  			swal('正在下载，请稍等...')
  		}
  	</script>
  	<script type="text/javascript" src="{% static 'novel/js/jquery-3.3.1.min.js' %}"></script>
  	<!-- Bootstrap部分： -->
  	<script type="text/javascript" src="{% static 'novel/js/bootstrap.min.js' %}"></script>

  </body>
  </html>